### ISSUE TITLE
Add Postgres DB/Docker compose 

### ISSUE THREAD

**Issue by jayceslesar** [MegaAntiCheat/api#2]
Something like the following, as well as `alembic` (no ORM here just SQL and Pydantic models will be used for interacting with an object in a python way is all.)

Would be nice to get some ansbile in terms of deploying + backing up on a cron but that can come in a later PR

```yaml
services:
  postgres:
    image: "postgres:16.1"
    environment:
      POSTGRES_DB: "dbase"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD_FILE: "/run/secrets/dbpass"
      PGDATA: "/var/lib/postgresql/data"
    secrets:
      - dbpass
    volumes:
      - "./db-data:/var/lib/postgresql/data"

secrets:
  dbpass:
    file: ./secrets/dbpass.txt
```
